version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_OPTIONS: -P ${COMPOSE_PROFILES:-dev}
    container_name: app
    ports:
      - "8080:8080"
    environment:
      - SPRING_ACTIVE_PROFILE=${COMPOSE_PROFILES:-dev}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-learning_platform}
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_INIT=${DB_INIT:-never} # always - для запуска с данными
      - DB_DDL=${DB_DDL:-update} # create-drop - для удаления базы при остановке
      - API_DOC_ENABLED=${API_DOC_ENABLED:-false} # true - для включения Swagger UI
    restart: unless-stopped

  postgres:
    image: postgres:latest
    profiles: [prod]
    container_name: db
    environment:
      POSTGRES_DB: ${DB_NAME:-learning_platform}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: