spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:learning_platform}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:mysecretpassword}
  jpa:
    hibernate:
      ddl-auto: ${DB_DDL:update}
  sql:
    init:
      mode: ${DB_INIT:never}
springdoc:
  api-docs:
    enabled: ${API_DOC_ENABLED:false}
  swagger-ui:
    enabled: ${API_DOC_ENABLED:false}
app:
  http:
    cors:
      origins: ${APP_HTTP_CORS_ORIGINS:http://localhost:3000}
      methods: ${APP_HTTP_CORS_METHODS:GET,POST,PUT,DELETE,OPTIONS}
      headers: ${APP_HTTP_CORS_HEADERS:authorization,content-type}
      allow-credentials: ${APP_HTTP_CORS_ALLOW_CREDENTIALS:true}