spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:postgresql://localhost:5432/learning_platform
    username: postgres
    password: ${DB_PASSWORD:mysecretpassword}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        transaction:
          jta:
            platform: none
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE